[package]
name = "cowsay"
version = "0.1.2"
description = "cowsay is a program that generates ASCII pictures of a cow with a message"
readme = "README.md"
repository = "https://github.com/wapm-packages/cowsay"

[[module]]
name = "cowsay"
source = "target/wasm32-unknown-wasi/release/cowsay.wasm"
abi = "none"

[[command]]
name = "cowsay"
module = "cowsay"

[[command]]
name = "cowthink"
module = "cowsay"
