[module]
name = "cowsay"
version = "0.1.0"
description = "cowsay is a program that generates ASCII pictures of a cow with a message"
readme = "README.md"
repository = "https://github.com/wapm-packages/cowsay"
module = "target/wasm32-unknown-wasi/release/cowsay.wasm"

[[command]]
name = "cowsay"

[[command]]
name = "cowthink"
