[module]
name = "cowsay"
version = "0.1.0"
module = "target/wasm32-unknown-wasi/release/cowsay.wasm"
description = "cowsay is a program that generates ASCII pictures of a cow with a message"
readme = "README.md"

[[command]]
name = "cowsay"

[[command]]
name = "cowthink"
